/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#131315",
        "primary-fixed-dim": "#feb68d",
        "inverse-surface": "#e5e1e4",
        "starlight-white": "#FAFAFA",
        "surface-variant": "#353437",
        "on-primary": "#502406",
        "on-secondary-fixed": "#171b27",
        "on-primary-container": "#522608",
        "error-container": "#93000a",
        "copper-glow": "#E6A27E",
        "tertiary-container": "#9b9999",
        "secondary-fixed": "#dee2f2",
        "surface": "#131315",
        "on-secondary-fixed-variant": "#424754",
        "outline": "#9f8d84",
        "surface-container": "#201f22",
        "secondary": "#c2c6d6",
        "error": "#ffb4ab",
        "inverse-primary": "#875130",
        "surface-container-lowest": "#0e0e10",
        "void-black": "#000000",
        "secondary-container": "#424754",
        "on-secondary-container": "#b0b5c4",
        "surface-container-low": "#1c1b1d",
        "surface-container-high": "#2a2a2c",
        "tertiary-fixed": "#e5e2e1",
        "surface-tint": "#feb68d",
        "on-primary-fixed": "#321200",
        "on-secondary": "#2b303c",
        "outline-variant": "#52443c",
        "on-error": "#690005",
        "primary": "#feb68d",
        "surface-container-highest": "#353437",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#1b1b1b",
        "secondary-fixed-dim": "#c2c6d6",
        "deep-charcoal": "#121212",
        "on-background": "#e5e1e4",
        "primary-fixed": "#ffdbc9",
        "inverse-on-surface": "#313032",
        "surface-dim": "#131315",
        "on-surface": "#e5e1e4",
        "tertiary": "#c8c6c5",
        "on-primary-fixed-variant": "#6b3a1b",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary": "#303030",
        "surface-bright": "#39393b",
        "primary-container": "#cc8b65",
        "on-tertiary-fixed-variant": "#474746",
        "on-surface-variant": "#d7c2b8",
        "on-tertiary-container": "#323131"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem"
      },
      spacing: {
        "stack-md": "16px",
        "nav-rail-width": "64px",
        "stack-sm": "8px",
        "gutter": "24px",
        "side-panel-width": "320px",
        "margin-safe": "40px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "headline-md": ["\"Source Serif 4\""],
        "display-lg": ["\"Source Serif 4\""],
        "label-sm": ["Space Grotesk"],
        "headline-lg-mobile": ["\"Source Serif 4\""],
        "headline-lg": ["\"Source Serif 4\""],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "300" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
