"""add events.sequence_index

Revision ID: ef5362e51e02
Revises: 1fa5cd397cfc
Create Date: 2026-10-10 13:19:40.343404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5362e51e02'
down_revision: Union[str, None] = '1fa5cd397cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sequence_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # batch mode so the downgrade also works on SQLite builds without ALTER TABLE DROP COLUMN
    with op.batch_alter_table('events') as batch_op:
        batch_op.drop_column('sequence_index')
    # ### end Alembic commands ###
